numero = int(input('Digite um número: '))
print('O resultado da sua tabuada é: ')
print( '-' * 12)
print('{} x {:2} = {}'.format(numero, 1, numero*1))
print('{} x {:2} = {}'.format(numero, 2, numero*2))
print('{} x {:2} = {}'.format(numero, 3, numero*3))
print('{} x {:2} = {}'.format(numero, 4, numero*4))
print('{} x {:2} = {}'.format(numero, 5, numero*5))
print('{} x {:2} = {}'.format(numero, 6, numero*6))
print('{} x {:2} = {}'.format(numero, 7, numero*7))
print('{} x {:2} = {}'.format(numero, 8, numero*8))
print('{} x {:2} = {}'.format(numero, 9, numero*9))
print('{} x {:2} = {}'.format(numero, 10, numero*10))
print( '-' * 12)

#Outro jeito de fazer:
#print( '--------------------------')
#multiplicacao1= (numero * 1)
#print(str(numero) + ' x ' + ' 1 ' + ' = ' + str(multiplicacao1))
#multiplicacao2 = (numero * 2)
#print(str(numero) + ' x ' + ' 2 ' + ' = ' + str(multiplicacao2))
#multiplicacao3 = (numero * 3)
#print(str(numero) + ' x ' + ' 3 ' + ' = ' + str(multiplicacao3))
#multiplicacao4 = (numero * 4)
#print(str(numero) + ' x ' + ' 4 ' + ' = ' + str(multiplicacao4))
#multiplicacao5 = (numero * 5)
#print(str(numero) + ' x ' + ' 5 ' + ' = ' + str(multiplicacao5))
#multiplicacao6 = (numero * 6)
#print(str(numero) + ' x ' + ' 6 ' + ' = ' + str(multiplicacao6))
#multiplicacao7 = (numero * 7)
#print(str(numero) + ' x ' + ' 7 ' + ' = ' + str(multiplicacao7))
#multiplicacao8 = (numero * 8)
#print(str(numero) + ' x ' + ' 8 ' + ' = ' + str(multiplicacao8))
#multiplicacao9 = (numero * 9)
#print(str(numero) + ' x ' + ' 9 ' + ' = ' + str(multiplicacao9))
#multiplicacao10 = (numero * 10)
#print(str(numero) + ' x ' + ' 10 ' + ' = ' + str(multiplicacao10))
#print( '--------------------------')